server:
  port: 8081

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          default-label: gateway #rama
          uri: https://github.com/wilmerescobarb/microservices
          search-paths: config-data
